language: objective-c
osx_image: xcode8

before_script:
  - gem install run_loop --no-document --env-shebang --no-prerelease
  - gem install luffa --no-document --env-shebang --no-prerelease
  - luffa authorize

script:
  - bin/ci/cucumber.rb --tags @travis

notifications:
  email:
    recipients:
      - joshuajmoody@gmail.com
      - chris.fuentes@xamarin.com
    on_success: change
    on_failure: always
  slack:
    rooms:
      secure: BsIK9tjPfApxUgN6lb/LRCtff2mKJ2KxTn2VXUjDvXJc29v4qaybuL5FpL8wEUdo7OQLKP90yeUq6n+Oxi+ZGsilX2zsWRaj1WzkLu0VfqxTNn9vE440HL6BolSodfWNV9mPiSd3Cb2gHYkibchj8g525dmIC4iUP+G/niBx7HQ=
