variables:
  # When Agent.JobName matches this value (and the git ref is a tag), then
  # built artifacts will be published to Azure Blob Storage.
  AzurePublishWhen: "Mojave-Xcode-10.3"

trigger:
  tags:
    include:
    - '*'
  branches:
    include:
    - master
pr:
  branches:
    include:
    - master

jobs:

- job:
  strategy:
    matrix:
      Mojave-Xcode-10.3:
        IMAGE_POOL: 'macOS-10.14'
        XCODE_VERSION: '10.3'
      Mojave-Xcode-11.0:
        IMAGE_POOL: 'macOS-10.14'
        XCODE_VERSION: '11'
  pool:
    vmImage: $(IMAGE_POOL)

  steps:
  - script: |
      set -e
      sudo xcode-select --switch "/Applications/Xcode_$(XCODE_VERSION).app/Contents/Developer"
    displayName: "$(IMAGE_POOL) - Xcode $(XCODE_VERSION)"
    
  - script: |
      set -e
      ruby -v
      bundler -v
    displayName: "Ruby info"

  - script: gem install bundler -v 1.17.3
    displayName: "Install bundler 1.17.3"

  - script: |
      set -e
      echo -e "install: --no-document --env-shebang\nupdate:  --no-document --env-shebang" > ~/.gemrc
      bundle install
    displayName: "Bundle install"

  - script: |
      set -e
      git clone https://$(CalabashKeychainGitHubAccessToken)@github.com/xamarinhq/calabash-codesign.git
      calabash-codesign/apple/create-keychain.sh
    displayName: "Download and install keychain"
    
  - script: bundle _1.17.3_ install
    workingDirectory: 'CalSmokeApp'
    displayName: "CalSmokeApp bundle install"

  - script: make app-cal
    workingDirectory: 'CalSmokeApp'
    displayName: "Make app-cal"
  
  - script: make ipa-cal
    workingDirectory: 'CalSmokeApp'
    displayName: "Make ipa-cal"

  - script: bundle exec bin/ci/cucumber.rb
    displayName: "Cucumber tests"

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFiles: 'CalSmokeApp/reports/**/*.xml'
      failTaskOnFailedTests: true
    condition: always()
  
  - task: Bash@3
    inputs:
      targetType: filePath
      filePath: "./bin/ci/az-publish.sh"
    env:
      AZURE_STORAGE_ACCOUNT: $(AzureStorageAccount)
      AZURE_STORAGE_KEY: $(AzureStorageKey)
      AZURE_STORAGE_CONNECTION_STRING: $(AzureStorageConnectionString)
      SOURCE_BRANCH: $(Build.SourceBranch)
    displayName: "Publish to Azure Blob Storage"
    condition: and(succeeded(), eq(variables['Agent.JobName'], variables['AzurePublishWhen']), eq(variables['Build.SourceBranch'], 'master'))