source 'https://rubygems.org'

gem 'calabash-cucumber', '~> 0.13'
gem 'briar', '~> 1.2'
gem 'luffa', '~> 1.0', '>= 1.0.2'

gem 'rspec', '~> 3.0'

gem 'xcpretty', '~> 0.1'
gem 'rake', '~> 10.3'
gem 'bundler', '~> 1.6'
gem 'travis', '~> 1.7'
gem 'pry'
gem 'pry-nav'
