source 'https://rubygems.org'

gem 'calabash-cucumber', "0.19.1"
gem "xamarin-test-cloud", "2.0.0"
gem "cucumber", "~> 2.0"
gem 'retriable', '~> 2.0'
gem "run_loop", ">= 2.1.2"

# workflow and build tools
gem 'rake', '~> 10.3'
gem 'bundler', '~> 1.6'
gem 'xcpretty', '~> 0.1'
gem 'briar', "~> 2.0"

# rspec stack
gem 'rspec', '~> 3.0'

# Pin to 3.0.6; >= 3.1.0 requires ruby 2.2. This is guard dependency.
gem "listen", "3.0.6"
gem 'guard-rspec', '~> 4.3'
gem 'guard-bundler', '~> 2.0'
gem 'growl', '~> 1.0'
gem 'stub_env', '>= 1.0.1', '< 2.0'

# chronic
gem 'chronic', '>= 0.10', '< 1.0'

# pry
gem 'pry'
gem 'pry-nav'

# CI Stack
gem 'travis', '~> 1.7'
gem 'luffa', '~> 1.0', '>= 1.0.2'

