source 'https://rubygems.org'

gem 'calabash-cucumber', :github => "calabash/calabash-ios", :branch => "develop"
gem "cucumber", "7.1.0"
gem "run_loop", :github => "calabash/run_loop", :branch => "develop"
gem "json", "2.6.1"

# workflow and build tools
gem 'retriable', "2.0.2"
gem 'rake', "13.0.6"
gem 'bundler', "2.3.15"
gem 'xcpretty', "0.3.0"
gem "xamarin-test-cloud", "2.3.0"
gem 'rspec', "3.11.0"
gem 'chronic', "0.10.2"
gem 'pry', "0.14.1"
gem 'pry-nav', "1.0.0"
gem 'luffa', "2.1.0"
gem 'guard-rspec', "4.7.3"
gem 'guard-bundler', "3.0.0"
gem 'growl', "1.0.3"
gem 'stub_env', "1.0.4"
gem 'briar', "2.0.5"
gem "listen", "3.7.1"
