not_xtc:     --tags ~@not_xtc
not_sim:     --tags ~@simulator --tags ~@simulator_only
no_launch:   --tags ~@no_launch
iphone_only: --tags ~@ipad --tags ~@ipad_only
ipad_only:   --tags ~@iphone --tags ~@iphone_only

args:         --expand --backtrace --no-multiline
tags:        -p not_xtc -p not_sim -p no_launch

default:     -p tags -p args

travis:      -p tags -p args --tags @travis
wip:         -p tags -p args --tags @wip
flicker:     -p tags -p args --tags @flickering
iphone:      -p tags -p args -p iphone_only
ipad:        -p tags -p args -p ipad_only
crash:       -p tags -p args --tags @expect_crash
