@alerts_and_sheets
Feature: Alerts and Sheets
  In order to demonstrate interactions with alerts and sheets
  As a Calabash maintainer
  I want some Scenarios that show Calabash working with alerts

  # These are alerts and sheets that are presented by _your_
  # application using:
  #
  #   UIAlertView *alert = [[UIAlertView alloc] ...];
  #   [alert show];
  #
  #   UIActionSheetView *sheet = [[UIActionSheet alloc] ...];
  #   # Action sheets can be anchored in many ways; this is
  #   # just an example.
  #   [sheet showFromTabBar:self.tabBarController.tabBar];
  #
  # These are _not_ alerts generated by the OS on behalf of your
  # app.  Such alerts are also known as the "Privacy alerts".  You
  # can read more about interacting with UIAlerts presented by the
  # OS here:
  #
  # https://github.com/calabash/calabash-ios/wiki/Managing-Privacy-Alerts%3A--Location-Services%2C-APNS%2C-Contacts

  Background:  Get me to the third tab
    Given I see the third tab

  @alert
  Scenario: Touch OK button on alert
    When I touch the show alert button
    Then I see an alert
    Then I see the "Smoke Test!" alert
    And I wait for all animations to stop
    And I can dismiss the alert with the OK button

    @wip
  @alert
  Scenario: Verify the alert title, message, and buttons
    When I touch the show alert button
    Then I see an alert
    And the title of the alert is "Smoke Test!"
    And the message of the alert is "Another day, another iOS alert"
    And the left hand button is "Cancel"
    And the right hand button is "OK"
