source 'https://rubygems.org'

# use bundle and bundle config to specify local gem locations
# bundle config local.GEM_NAME /path/to/local/git/repository

# noinspection RailsParamDefResolve
#gem 'calabash-cucumber', :github => 'calabash/calabash-ios', :branch => 'master'
gem 'calabash-cucumber'
gem 'xcpretty', '~> 0.1'
gem 'rake', '~> 10.3'
